/**
 * Rebuilds `references/` from the published documentation.
 *
 * Every page on docs.colyseus.io is served as raw markdown at `<route>.md`.
 * This script assembles the bundled references from those, so the skill's API
 * detail is generated rather than hand-copied, and cannot quietly fall behind
 * a release.
 *
 * It also resolves every documentation URL mentioned in SKILL.md. A 404 there
 * means a page was renamed: the site's redirect map is client-side JavaScript
 * and does not rescue a raw fetch, so a stale URL is dead for the agent that
 * follows it. Better to fail here. The `references/<file> § "Heading"` section
 * pointers in SKILL.md are checked the same way against the generated files.
 *
 *   node tools/sync.mjs            # rewrite references/
 *   node tools/sync.mjs --check    # fail if references/ is out of date
 *
 * DOCS_ORIGIN overrides the source. Point it at a local `out/` directory to
 * test against an unpublished docs build:
 *
 *   DOCS_ORIGIN=../docs/out node tools/sync.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const referencesDir = path.join(root, 'references')

const ORIGIN = process.env.DOCS_ORIGIN || 'https://docs.colyseus.io'
const remote = /^https?:\/\//.test(ORIGIN)
const check = process.argv.includes('--check')

/** Fetch one page as markdown, from the site or from a local docs build. */
async function fetchPage(route) {
    const rel = `${route === '/' ? '/index' : route}.md`
    if (!remote) {
        const file = path.join(ORIGIN, rel)
        if (!fs.existsSync(file)) throw new Error(`not found: ${file}`)
        return fs.readFileSync(file, 'utf8')
    }
    const res = await fetch(ORIGIN + rel)
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${ORIGIN}${rel}`)
    return res.text()
}

const sources = JSON.parse(fs.readFileSync(path.join(root, 'sources.json'), 'utf8'))
const failures = []
const stale = []

for (const [name, routes] of Object.entries(sources.references)) {
    const parts = []
    for (const route of routes) {
        try {
            parts.push(await fetchPage(route))
        } catch (err) {
            failures.push(`${name} <- ${route}: ${err.message}`)
        }
    }
    if (parts.length !== routes.length) continue // don't write a truncated reference

    const content = [
        `<!-- Generated by tools/sync.mjs from ${routes.join(', ')}. Do not edit. -->`,
        '',
        ...parts,
    ].join('\n')

    const file = path.join(referencesDir, name)
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
    if (current === content) continue

    if (check) stale.push(name)
    else {
        fs.mkdirSync(referencesDir, { recursive: true })
        fs.writeFileSync(file, content)
    }
}

// Every doc URL the skill hands to an agent must actually resolve.
const skill = fs.readFileSync(path.join(root, 'SKILL.md'), 'utf8')
const linked = [...new Set([...skill.matchAll(/https:\/\/docs\.colyseus\.io(\/[\w./-]*)\.md/g)].map((m) => m[1]))]

for (const route of linked) {
    try {
        await fetchPage(route)
    } catch (err) {
        failures.push(`SKILL.md links a page that does not resolve: ${err.message}`)
    }
}

// Every `references/<file> § "Heading"` pointer must name a real section, or
// the agent that jumps to it lands nowhere. Headings come from the docs, so a
// renamed heading upstream fails here, like a renamed page does above.
const headingText = (line) => line.replace(/^#+\s*/, '').replace(/`/g, '').trim()
const pointers = new Map()
for (const [, file, heading] of skill.matchAll(/references\/([\w.-]+\.md) § "([^"]+)"/g)) pointers.set(`${file} § ${heading}`, { file, heading })

for (const { file, heading } of pointers.values()) {
    const target = path.join(referencesDir, file)
    if (!fs.existsSync(target)) {
        failures.push(`SKILL.md points at a reference that does not exist: ${file}`)
        continue
    }
    const headings = fs.readFileSync(target, 'utf8').split('\n').filter((l) => /^#{1,6} /.test(l)).map(headingText)
    if (!headings.includes(heading)) failures.push(`SKILL.md points at a section that does not exist: ${file} § "${heading}"`)
}

for (const f of failures) console.error(`  ${f}`)

if (failures.length) {
    console.error(`\n✗ ${failures.length} unresolved: a page or section was renamed or removed`)
    process.exit(1)
}
if (stale.length) {
    console.error(`\n✗ stale: ${stale.join(', ')}. Run \`npm run sync\` and commit the result`)
    process.exit(1)
}

const count = Object.keys(sources.references).length
console.log(`✓ ${check ? 'up to date' : 'synced'}: ${count} references, ${linked.length} linked pages and ${pointers.size} section pointers resolve`)
